version: '3.4'

services:
  library:
    image: ${DOCKER_REGISTRY-}library
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    ports:
        - "51930:80"
    depends_on: 
        - mysqldocker
  
  mysqldocker:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - D:\Dados\volumes\mysql:/var/opt/mysql/data
    ports:
      - "3307:3306"