version: '3.8'

services:
  library:
    image: ${DOCKER_REGISTRY-}library
    build:
      context: .
      dockerfile: .
    ports:
       #- "80:80"
       - "443:443"
    depends_on: 
        - mysqldocker
  
  mysqldocker:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - /var/lib/mysql:/var/opt/mysql/data
    ports:
      - "3307:3306"