version: '3.4'

services:
  library.api:
        image: ${DOCKER_REGISTRY-}library
        build:
            context: .
            dockerfile: .
        ports:
            - "8081:80"



  db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: 
        ports:
            - "8080:8080"