version: '3.4'

services:
  library.api:
    image: ${DOCKER_REGISTRY-}library
    build:
      context: .
      dockerfile: .
    ports:
     - "8081:80"    
    depends_on:
      - my-sql-docker

  my-sql-docker:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - D:\Dados\volumes\mysql:/var/opt/mysql/data
    ports:
      - "3307:3306"